# Generated by Django 5.1.5 on 2025-02-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="course_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="api.coursecontent",
            ),
        ),
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
    ]
