# Generated by Django 5.1.5 on 2025-03-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="lessoncompletion",
            unique_together={("lesson", "student")},
        ),
    ]
