# Generated by Django 5.1.5 on 2025-02-06 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="regis_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
