# Generated by Django 5.1.5 on 2025-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="thumbnail_url",
            field=models.URLField(default=None, null=True),
        ),
    ]
