# Generated by Django 5.1.5 on 2025-02-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("video_id", models.CharField(max_length=50)),
                (
                    "subtitle_vi_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "attachment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="api.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
