# Generated by Django 5.1.5 on 2025-02-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_course_thumbnail_id_lesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
