# Generated by Django 5.1.5 on 2025-01-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
