# Generated by Django 5.1.5 on 2025-02-10 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_category_alter_chapter_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="teacher",
            new_name="teacher_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_visible",
        ),
        migrations.RemoveField(
            model_name="course",
            name="max_students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
        migrations.RemoveField(
            model_name="course",
            name="regis_end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="regis_start_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(related_name="courses", to="api.category"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator with full access"),
                    ("teacher", "Teacher with access to course management"),
                    ("student", "Student with access to enrolled courses"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CourseDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField(default=0)),
                ("discount", models.FloatField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_date", models.DateTimeField()),
                (
                    "regis_start_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("regis_end_date", models.DateTimeField()),
                ("max_students", models.IntegerField(blank=True, null=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "CourseDetail",
                "verbose_name_plural": "CourseDetails",
                "db_table": "course_details",
            },
        ),
    ]
