# Generated by Django 5.1.5 on 2025-02-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_teacher_course_teacher_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="coursedetail",
            old_name="course_id",
            new_name="course",
        ),
    ]
