# Generated by Django 5.1.5 on 2025-02-11 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_teacher_id_course_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetail",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
