# Generated by Django 5.1.4 on 2025-01-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
