# Generated by Django 5.1.5 on 2025-02-13 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_payment_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(null=True)),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField(null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
            },
        ),
    ]
