# Generated by Django 5.1.5 on 2025-02-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="api.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Score",
                "verbose_name_plural": "Submission Scores",
                "db_table": "submission_scores",
            },
        ),
    ]
