# Generated by Django 5.1.5 on 2025-02-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_lessoncompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("complete", "complete"), ("failed", "failed")],
                default="complete",
                max_length=10,
            ),
        ),
    ]
