"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Load environment variables from .env file
# Supabase variables
SUPABASE_PROJECT_ID=config('SUPABASE_PROJECT_ID')
SUPABASE_PROJECT_URL=config('SUPABASE_PROJECT_URL')
SUPABASE_ANON_KEY=config('SUPABASE_ANON_KEY')
SUPABASE_SERVICE_ROLE_KEY=config('SUPABASE_SERVICE_ROLE_KEY')
SUPABASE_JWT_SECRET=config('SUPABASE_JWT_SECRET')

# Subpabase database variables - PostgreSQL
SUPABASE_DB_HOST=config('SUPABASE_DB_HOST')
SUPABASE_DB_PORT=config('SUPABASE_DB_PORT', cast=int)
SUPABASE_DB_NAME=config('SUPABASE_DB_NAME')
SUPABASE_DB_USER=config('SUPABASE_DB_USER')
SUPABASE_DB_PASSWORD=config('SUPABASE_DB_PASSWORD')

# Supabase storage variables
SUPABASE_STORAGE_PUBLIC_BUCKET=config('SUPABASE_STORAGE_PUBLIC_BUCKET')
SUPABASE_STORAGE_PRIVATE_BUCKET=config('SUPABASE_STORAGE_PRIVATE_BUCKET')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "api",
    'drf_yasg', # Swagger
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware"
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://192.168.1.4:3000",  # Thay bằng IP và cổng của Next.js
    "http://localhost:3000",      # Nếu chạy local trên máy chính
]

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.4']

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': SUPABASE_DB_NAME,
        'USER': SUPABASE_DB_USER,
        'PASSWORD': SUPABASE_DB_PASSWORD,
        'HOST': SUPABASE_DB_HOST,
        'PORT': SUPABASE_DB_PORT,
        'OPTIONS': {
            'sslmode': 'require',  # Require SSL connection for Supabase
        },
    }
}

# AUTH_USER_MODEL = 'api.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.middlewares.authentication.SupabaseJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny'
    ],
    'EXCEPTION_HANDLER': 'api.exceptions.exception_handler.custom_exception_handler'
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Nếu bạn đang chạy local và chưa cấu hình file tĩnh:   
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "[{levelname}] {name} - {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        # Logger cho các app cụ thể
        "django": {
            "handlers": ["console"],
            "level": "WARNING", 
            "propagate": False,
        },
        "api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
